"""Initial schema — autogenerated from SQLAlchemy models

Revision ID: 001_initial
Revises:
Create Date: 2026-05-07 00:00:00.000000

Autogenerated from iam_substrate.substrate_api.models (Base.metadata) reflecting
the current stable schema deployed to myntist-beacon-db.
Tables: identities, telemetry, iam_substrate_log, iam_temporal_events, field_telemetry.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "identities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("S", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("Q", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("tau", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("nabla_phi", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("delta_S", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("field_state", sa.String(), nullable=False, server_default="stable"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "telemetry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identity_id", sa.String(), nullable=False),
        sa.Column("S", sa.Float(), nullable=False),
        sa.Column("delta_S", sa.Float(), nullable=False),
        sa.Column("Q", sa.Float(), nullable=False),
        sa.Column("tau", sa.Float(), nullable=False),
        sa.Column("nabla_phi", sa.Float(), nullable=False),
        sa.Column("field_state", sa.String(), nullable=False),
        sa.Column("mttr", sa.Float(), nullable=True),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.Column("liquidity_signal", sa.Float(), nullable=True),
        sa.Column("coherence_signal", sa.Float(), nullable=True),
        sa.Column("admitted", sa.Boolean(), nullable=True),
        sa.Column("active_policies", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_telemetry_recorded_at", "telemetry", ["recorded_at"])

    op.create_table(
        "iam_substrate_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identity_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("S_before", sa.Float(), nullable=True),
        sa.Column("S_after", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_iam_substrate_log_created_at", "iam_substrate_log", ["created_at"])
    op.create_index("ix_iam_substrate_log_identity_id", "iam_substrate_log", ["identity_id"])

    op.create_table(
        "iam_temporal_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identity_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("S", sa.Float(), nullable=True),
        sa.Column("D", sa.Float(), nullable=True),
        sa.Column("Ttau", sa.Float(), nullable=True),
        sa.Column("admitted", sa.Boolean(), nullable=True),
        sa.Column("active_policies", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "field_telemetry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identity_id", sa.String(), nullable=True),
        sa.Column("S", sa.Float(), nullable=True),
        sa.Column("delta_S", sa.Float(), nullable=True),
        sa.Column("Q", sa.Float(), nullable=True),
        sa.Column("tau", sa.Float(), nullable=True),
        sa.Column("nabla_phi", sa.Float(), nullable=True),
        sa.Column("field_state", sa.String(), nullable=True),
        sa.Column("float_yield", sa.Float(), nullable=True),
        sa.Column("liquidity_signal", sa.Float(), nullable=True),
        sa.Column("coherence_signal", sa.Float(), nullable=True),
        sa.Column("r_HSCE", sa.Float(), nullable=True),
        sa.Column("float_reinvestment_rate", sa.Float(), nullable=True),
        sa.Column("schema_version", sa.String(), nullable=True),
        sa.Column("time", sa.DateTime(), server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_field_telemetry_time", "field_telemetry", ["time"])


def downgrade() -> None:
    op.drop_table("field_telemetry")
    op.drop_table("iam_temporal_events")
    op.drop_table("iam_substrate_log")
    op.drop_table("telemetry")
    op.drop_table("identities")
